export const HOME_SCREEN = 'HOME_SCREEN';
export const FRIENDS_SCREEN = 'FRIENDS_SCREEN';
export const FRIENDS_LIST = 'FRIENDS_LIST';
export const FRIEND_DETAILS_SCREEN = 'FRIEND_DETAILS_SCREEN';
export const SETTINGS_SCREEN = 'SETTINGS_SCREEN';
export const ADD_FRIEND_SCREEN = 'ADD_FRIEND_SCREEN';
